# Generated by Django 4.2.5 on 2023-09-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_diesel_fuel', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Стоимость дизельного топлива')),
                ('altitude', models.IntegerField(verbose_name='Высота над уровнем моря')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Долгота')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Заправка',
                'verbose_name_plural': 'Заправки',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=155, verbose_name='Начальная точка')),
                ('end_point', models.CharField(max_length=155, verbose_name='Конечная точка')),
                ('time', models.DurationField(verbose_name='Общее время')),
                ('distance', models.IntegerField(verbose_name='Общая дистанция')),
                ('link_to_route', models.CharField(max_length=255, verbose_name='Ссылка на маршрут')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RouteGasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_stations', models.ManyToManyField(to='navigation.gasstation', verbose_name='Заправки')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.route', verbose_name='Маршрут')),
            ],
        ),
    ]
