# Generated by Django 4.2.5 on 2023-09-17 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_diesel_fuel', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Стоимость дизельного топлива')),
                ('altitude', models.IntegerField(verbose_name='Высота над уровнем моря')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Долгота')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Заправка',
                'verbose_name_plural': 'Заправки',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название маршрута')),
                ('title', models.TextField(verbose_name='Описание маршрута')),
                ('time', models.DurationField(blank=True, null=True, verbose_name='Общее время')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Общая дистанция')),
                ('route', models.JSONField(blank=True, null=True, verbose_name='Координаты маршрута')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RouteCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название точки')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Координата',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='RouteGasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_stations', models.ManyToManyField(to='navigation.gasstation', verbose_name='Заправки')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.route', verbose_name='Маршрут')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='end_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='navigation.routecoordinate', verbose_name='Конечная точка'),
        ),
        migrations.AddField(
            model_name='route',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='navigation.routecoordinate', verbose_name='Начальная точка'),
        ),
    ]
