# Generated by Django 4.2.5 on 2023-09-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='time',
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Общее время'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Общая дистанция'),
        ),
    ]
