# Generated by Django 4.2.5 on 2023-09-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Долгота'),
        ),
    ]
