# Generated by Django 4.2.5 on 2023-09-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_remove_route_time_route_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Общая дистанция'),
        ),
    ]
