# Generated by Django 4.2.5 on 2023-09-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_alter_routegasstation_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='nearest_road_points',
        ),
        migrations.RemoveField(
            model_name='route',
            name='gas_stations',
        ),
    ]
